In [29]:
import sys
sys.path.append('../../')
sys.path.append('../../potzy/')
%run 'header.ipynb'
from morningstarreader import *
import time

In [ ]:
# terminal PE from growth and pd

In [25]:
#calculate growth
income_start = 100
income_end = 160
payout = 0.1
nyears = 5

#income_start*((1+g)*(1-payout))**nyears = income_end

In [26]:
1.1**5

1.6105100000000006

In [27]:
growth=((income_end/income_start)**(1/nyears)/(1-payout))-1
print(growth)

0.22062282589568638

In [40]:
pd.read_html("http://financials.morningstar.com/ratios/r.html?t=MKC&region=usa&culture=en-US")

ValueError: No tables found

In [30]:
kr = KeyRatioData()
kr.load_data('XNYS:MKC','us')

In [47]:
df=kr.get_data('XNYS:MKC','us')

In [49]:
df.head(40)

,2008-11,2009-11,2010-11,2011-11,2012-11,2013-11,2014-11,2015-11,2016-11,2017-11,TTM
item,,,,,,,,,,,
Revenue USD Mil,"3,176","3,192","3,337","3,697","4,014","4,123","4,243","4,296","4,412","4,834","5,028"
Gross Margin %,40.6,41.6,42.5,41.2,40.3,40.4,40.8,40.4,41.5,41.6,42.1
Operating Income USD Mil,418,481,510,540,578,590,608,609,657,765,814
Operating Margin %,13.1,15.1,15.3,14.6,14.4,14.3,14.3,14.2,14.9,15.8,16.2
Net Income USD Mil,256,300,370,374,408,389,437,402,472,477,807
Earnings Per Share USD,1.94,2.27,2.75,2.79,3.04,2.91,3.34,3.11,3.69,3.72,6.16
Dividends USD,0.88,0.96,1.04,1.12,1.24,1.36,1.48,1.60,1.72,1.88,1.93
Payout Ratio % *,43.4,42.2,37.8,40.1,40.7,43.6,45.6,51.0,46.6,51.1,32.7
Shares Mil,132,132,134,134,134,133,131,129,128,128,130
Book Value Per Share * USD,9.34,10.13,10.92,12.05,12.70,13.60,15.21,13.71,14.03,19.25,23.31
Operating Cash Flow USD Mil,315,416,388,340,455,465,504,590,658,815,751
Cap Spending USD Mil,-85,-82,-89,-97,-110,-100,-132,-128,-154,-182,-184
Free Cash Flow USD Mil,229,333,299,243,344,365,370,462,504,632,566
Free Cash Flow Per Share * USD,1.76,2.52,2.22,1.81,2.57,2.42,2.96,3.24,3.50,3.65,NaN
Working Capital USD Mil,-65,152,181,229,97,307,294,166,-1,-330,NaN
Key Ratios -> Profitability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Margins % of Sales,2008-11,2009-11,2010-11,2011-11,2012-11,2013-11,2014-11,2015-11,2016-11,2017-11,TTM
Revenue,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
COGS,59.45,58.42,57.51,58.82,59.70,59.60,59.22,59.56,58.48,58.42,57.89
Gross Margin,40.55,41.58,42.49,41.18,40.30,40.40,40.78,40.44,41.52,41.58,42.11
SG&A,27.41,26.52,27.21,26.56,25.90,26.07,26.44,26.24,26.63,25.75,25.93
R&D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Margin,13.15,15.06,15.28,14.61,14.41,14.33,14.33,14.20,14.89,15.83,16.18
Net Int Inc & Other,-2.51,-2.01,-1.41,-1.32,-1.30,-2.22,-1.27,-2.65,-1.53,-3.53,-3.88
EBT Margin,10.63,13.05,13.87,13.29,13.11,12.11,13.07,11.55,13.36,12.30,12.30
Profitability,2008-11,2009-11,2010-11,2011-11,2012-11,2013-11,2014-11,2015-11,2016-11,2017-11,TTM
Tax Rate %,29.78,31.93,25.50,29.02,26.57,26.75,26.32,26.46,25.97,25.44,NaN
Net Margin %,8.05,9.39,11.09,10.12,10.16,9.43,10.32,9.35,10.71,9.88,16.04
Asset Turnover (Average),1.06,0.97,0.98,0.98,0.97,0.96,0.96,0.96,0.96,0.64,0.67
Return on Assets %,8.52,9.07,10.88,9.97,9.88,9.03,9.88,9.00,10.33,6.36,10.67
Financial Leverage (Average),3.05,2.54,2.35,2.55,2.48,2.30,2.46,2.69,2.85,4.06,3.39
Return on Equity %,23.90,25.09,26.55,24.49,24.83,21.52,23.51,23.20,28.65,22.81,33.75
Return on Invested Capital %,12.47,14.53,17.47,15.83,15.69,14.22,15.20,14.35,16.74,10.29,15.49
Interest Coverage,NaN,8.89,10.39,10.60,10.64,10.37,12.15,10.31,11.52,7.22,6.03
Key Ratios -> Growth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,2008-11,2009-11,2010-11,2011-11,2012-11,2013-11,2014-11,2015-11,2016-11,2017-11,Latest Qtr
Revenue %,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year over Year,8.93,0.49,4.53,10.81,8.56,2.72,2.91,1.25,2.68,9.58,18.53
3-Year Average,7.01,5.53,4.59,5.19,7.94,7.31,4.69,2.29,2.28,4.44,NaN

In [53]:
item = 'Free Cash Flow USD Mil'
dff=df.loc[item,:].astype(float)

In [56]:
N=5
dff.pct_change(periods=N).apply(lambda x: (x+1)**(1/N)-1)

2008-11         NaN
2009-11         NaN
2010-11         NaN
2011-11         NaN
2012-11         NaN
2013-11    0.097720
2014-11    0.021296
2015-11    0.090923
2016-11    0.157084
2017-11    0.129358
TTM        0.091704
Name: Free Cash Flow USD Mil, dtype: float64